In [1]:
## Here in this notebook we're going to work on the linear regression
## Using numpy[First principle], torch's tensor, neural network and then with an inbuilt pytorch module

## so lets get started.....
import numpy as np
import torch as tr
import matplotlib.pyplot as plt
%matplotlib inline 

In [2]:
## So the base equation that we'll be working with will be
## y_t = 2*x_t - 3*x_t**2 + 1, for over 30 samples

from numpy.random import random


In [3]:
## Generate random data
x = random((30,2))
## generate labels corresponding to input data x
y = np.dot(x,[2., -3.,]) + 1
w_source = np.array([2., -3.])
b_source = np.array([1.])

x[:5]



array([[0.52541219, 0.50299945],
       [0.98215495, 0.02098079],
       [0.59093436, 0.78980699],
       [0.83408857, 0.50300441],
       [0.78223817, 0.07051406]])

In [4]:
from mpl_toolkits.mplot3d import Axes3D

def plot_figs(fig_num, elev, azim, x, y, weights, bias):
    fig = plt.figure(fig_num, figsize=(4,3))
    plt.clf()
    ax = Axes3D(fig, elev=elev, azim=azim)
    ax.scatter(x[:,0],x[:,1], y)
    ax.plot_surface(np.array([[0,0],[1,1]]), 
                   np.array([[0,1],[0,1]]),
                    (np.dot(np.array([[0,0,1,1],[0,1,0,1]]).T, weights) + bias).reshape(2,2), alpha=0.5)
    ax.set_xlabel('x_1')
    ax.set_ylabel('x_2')
    ax.set_zlabel('y')

def plot_views(x,y,w,b):
    elev = 43.5
    azim = -110
    plot_figs(1,elev, azim, x, y, w,b[0])
    plt.show()
    
    
    
    

In [5]:
plot_views(x,y, w_source, b_source)

<Figure size 400x300 with 0 Axes>

In [6]:
w_init = random(2)
b_init = random(1)

w = w_init
b = b_init
print("Initial Values of the Parameters: ", w, b)


Initial Values of the Parameters:  [0.45424486 0.72050176] [0.65662812]


In [7]:
## Lets define our functions
## Forward function
def forward(x):
    return x.dot(w)+b
## loss functions
def loss(x,y):
    y_pred = forward(x)
    return (y - y_pred)**2

print("Initial loss:: ", np.sum([loss(x_val, y_val) for x_val, y_val in zip(x,y)]))


## compute gradients
def gradient(x,y):
    return 2*(x.dot(w)+b - y)*x, 2*(x.dot(w)+b - y) 

learning_rate = 1e-2
## Training loop


for epoch in range(70):
    grad_w = np.array([0,0])
    grad_b = np.array(0)
    l = 0
    for x_val, y_val in zip(x,y):
        grad_w = np.add(grad_w, gradient(x_val, y_val)[0])
        grad_b = np.add(grad_b, gradient(x_val, y_val)[1])
        l += loss(x_val, y_val)
    
    w = w - learning_rate*grad_w
    b = b - learning_rate*grad_b
    print("Progress:: ","epoch:: ",epoch,"loss",l[0])

## After Training
print("Estimation of the parameters:: ", w,b)





Initial loss::  55.44930233162283
Progress::  epoch::  0 loss 55.44930233162283
Progress::  epoch::  1 loss 41.74773264909031
Progress::  epoch::  2 loss 36.38628814576933
Progress::  epoch::  3 loss 31.899432402164276
Progress::  epoch::  4 loss 27.991779310488575
Progress::  epoch::  5 loss 24.58311765705068
Progress::  epoch::  6 loss 21.608707915949473
Progress::  epoch::  7 loss 19.012372319331345
Progress::  epoch::  8 loss 16.74524038881043
Progress::  epoch::  9 loss 14.764793481642629
Progress::  epoch::  10 loss 13.034037674785948
Progress::  epoch::  11 loss 11.520784509294991
Progress::  epoch::  12 loss 10.19702543426205
Progress::  epoch::  13 loss 9.038387738735992
Progress::  epoch::  14 loss 8.023661354214022
Progress::  epoch::  15 loss 7.134387293856239
Progress::  epoch::  16 loss 6.3544996977611214
Progress::  epoch::  17 loss 5.670014500045032
Progress::  epoch::  18 loss 5.06875864352215
Progress::  epoch::  19 loss 4.540134559250464
Progress::  epoch::  20 loss 

**Lets do the same with Pytorch Tensors**

In [8]:
## Linear Regression with tensors
dtype = tr.FloatTensor
x_t = tr.from_numpy(x).type(dtype)
y_t = tr.from_numpy(y).type(dtype).unsqueeze(1)


In [9]:
print(x_t, y_t)

tensor([[0.5254, 0.5030],
        [0.9822, 0.0210],
        [0.5909, 0.7898],
        [0.8341, 0.5030],
        [0.7822, 0.0705],
        [0.3508, 0.0503],
        [0.5284, 0.0654],
        [0.2686, 0.6132],
        [0.4547, 0.5046],
        [0.9771, 0.0229],
        [0.0915, 0.5195],
        [0.9731, 0.1173],
        [0.9066, 0.2760],
        [0.5495, 0.8158],
        [0.4425, 0.4475],
        [0.0387, 0.0710],
        [0.4897, 0.5664],
        [0.0101, 0.7234],
        [0.3933, 0.8477],
        [0.6492, 0.3869],
        [0.1898, 0.4523],
        [0.1010, 0.4918],
        [0.1009, 0.8102],
        [0.4745, 0.3107],
        [0.1932, 0.6181],
        [0.0079, 0.2781],
        [0.2715, 0.4195],
        [0.6589, 0.2593],
        [0.2409, 0.8576],
        [0.3370, 0.0107]]) tensor([[ 0.5418],
        [ 2.9014],
        [-0.1876],
        [ 1.1592],
        [ 2.3529],
        [ 1.5507],
        [ 1.8605],
        [-0.3025],
        [ 0.3957],
        [ 2.8855],
        [-0.3755],
        [ 

In [10]:
w_init_t = tr.from_numpy(w_init).type(dtype)
b_init_t = tr.from_numpy(b_init).type(dtype)

# print(w_init_t, b_init_t)
w_t = w_init_t.clone()
# print(w_t, w_t.ndim)
w_t.unsqueeze_(1)
# print(w_t, w_t.ndim)
b_t = b_init_t.clone()
# print(b_t)
b_t.unsqueeze_(1)
print("Initial Values of the parameters : ", w_t, b_t)


Initial Values of the parameters :  tensor([[0.4542],
        [0.7205]]) tensor([[0.6566]])


In [11]:
## Forward Pass
def forward_t(x):
    return x.mm(w_t)+b_t
## Loss Function
def loss_t(x,y):
    y_pred = forward_t(x)
    return (y_pred - y).pow(2).sum()
## compute gradient
def gradient_t(x,y):
    return 2*tr.mm(tr.t(x), x.mm(w_t)+b_t - y), 2*(x.mm(w_t)+b_t - y).sum()

learning_rate = 1e-2
for epoch in range(70):
    l_t = loss_t(x_t, y_t)
    grad_w, grad_b = gradient_t(x_t, y_t)
    w_t = w_t - learning_rate * grad_w
    b_t = b_t - learning_rate * grad_b
    print("Progress: ","Epoch: ", epoch,"__","Loss: ",l_t)

print("estimation of the parameters:: ", w_t, b_t)

Progress:  Epoch:  0 __ Loss:  tensor(55.4493)
Progress:  Epoch:  1 __ Loss:  tensor(41.7477)
Progress:  Epoch:  2 __ Loss:  tensor(36.3863)
Progress:  Epoch:  3 __ Loss:  tensor(31.8994)
Progress:  Epoch:  4 __ Loss:  tensor(27.9918)
Progress:  Epoch:  5 __ Loss:  tensor(24.5831)
Progress:  Epoch:  6 __ Loss:  tensor(21.6087)
Progress:  Epoch:  7 __ Loss:  tensor(19.0124)
Progress:  Epoch:  8 __ Loss:  tensor(16.7452)
Progress:  Epoch:  9 __ Loss:  tensor(14.7648)
Progress:  Epoch:  10 __ Loss:  tensor(13.0340)
Progress:  Epoch:  11 __ Loss:  tensor(11.5208)
Progress:  Epoch:  12 __ Loss:  tensor(10.1970)
Progress:  Epoch:  13 __ Loss:  tensor(9.0384)
Progress:  Epoch:  14 __ Loss:  tensor(8.0237)
Progress:  Epoch:  15 __ Loss:  tensor(7.1344)
Progress:  Epoch:  16 __ Loss:  tensor(6.3545)
Progress:  Epoch:  17 __ Loss:  tensor(5.6700)
Progress:  Epoch:  18 __ Loss:  tensor(5.0688)
Progress:  Epoch:  19 __ Loss:  tensor(4.5401)
Progress:  Epoch:  20 __ Loss:  tensor(4.0749)
Progress: 

**Linear Regression with AutoGrad**

In [12]:
w_v = w_init_t.clone().unsqueeze(1)
w_v.requires_grad_(True)
b_v = b_init_t.clone().unsqueeze(1)
b_v.requires_grad_(True)
print("initial values of the parameters: ", w_v.data, b_v.data)


initial values of the parameters:  tensor([[0.4542],
        [0.7205]]) tensor([[0.6566]])


In [13]:
for epoch in range(70):
    y_pred = x_t.mm(w_v)+b_v
    loss = (y_pred - y_t).pow(2).sum()
    
    loss.backward()
    
    with tr.no_grad():
        w_v -= learning_rate * w_v.grad
        b_v -= learning_rate * b_v.grad
    
    w_v.grad.zero_()
    b_v.grad.zero_()
    
    print("Progress: ", "epoch: ", "loss: ", loss.data.item())

print("estimation of the parameters: ", w_v.data, b_v.data.t())

Progress:  epoch:  loss:  55.44930648803711
Progress:  epoch:  loss:  41.74773025512695
Progress:  epoch:  loss:  36.386287689208984
Progress:  epoch:  loss:  31.89943504333496
Progress:  epoch:  loss:  27.991777420043945
Progress:  epoch:  loss:  24.583118438720703
Progress:  epoch:  loss:  21.60870933532715
Progress:  epoch:  loss:  19.012374877929688
Progress:  epoch:  loss:  16.7452392578125
Progress:  epoch:  loss:  14.764793395996094
Progress:  epoch:  loss:  13.034037590026855
Progress:  epoch:  loss:  11.520784378051758
Progress:  epoch:  loss:  10.197025299072266
Progress:  epoch:  loss:  9.038389205932617
Progress:  epoch:  loss:  8.023661613464355
Progress:  epoch:  loss:  7.134387493133545
Progress:  epoch:  loss:  6.354499816894531
Progress:  epoch:  loss:  5.670013904571533
Progress:  epoch:  loss:  5.068758964538574
Progress:  epoch:  loss:  4.540134906768799
Progress:  epoch:  loss:  4.074915409088135
Progress:  epoch:  loss:  3.665066957473755
Progress:  epoch:  loss: 

**Linear Regression with Neural Network with Pytorch**

In [14]:
model = tr.nn.Sequential(
tr.nn.Linear(2,1),
    
)

for m in model.children():
    m.weight.data = w_init_t.clone().unsqueeze(0)
    m.bias.data = b_init_t.clone()

loss_fn = tr.nn.MSELoss(reduction='sum')

model.train()


for epoch in range(70):
    y_pred = model(x_t)
    
    loss = loss_fn(y_pred, y_t)
    
    model.zero_grad()
    
    loss.backward()
    
    with tr.no_grad():
        for param in model.parameters():
            param.data -= learning_rate * param.grad
    
    print("Progress : ", "epoch: ", epoch, "loss: ", loss.data.item())

print("estimation of the parameter:  ")
for param in model.parameters():
    print(param)
    

Progress :  epoch:  0 loss:  55.44930648803711
Progress :  epoch:  1 loss:  41.74773025512695
Progress :  epoch:  2 loss:  36.386287689208984
Progress :  epoch:  3 loss:  31.89943504333496
Progress :  epoch:  4 loss:  27.991777420043945
Progress :  epoch:  5 loss:  24.583118438720703
Progress :  epoch:  6 loss:  21.60870933532715
Progress :  epoch:  7 loss:  19.012374877929688
Progress :  epoch:  8 loss:  16.7452392578125
Progress :  epoch:  9 loss:  14.764793395996094
Progress :  epoch:  10 loss:  13.034037590026855
Progress :  epoch:  11 loss:  11.520784378051758
Progress :  epoch:  12 loss:  10.197025299072266
Progress :  epoch:  13 loss:  9.038389205932617
Progress :  epoch:  14 loss:  8.023661613464355
Progress :  epoch:  15 loss:  7.134387493133545
Progress :  epoch:  16 loss:  6.354499816894531
Progress :  epoch:  17 loss:  5.670013904571533
Progress :  epoch:  18 loss:  5.068758964538574
Progress :  epoch:  19 loss:  4.540134906768799
Progress :  epoch:  20 loss:  4.07491540908

****

In [15]:
model = tr.nn.Sequential(
tr.nn.Linear(2,1))
for m in model.children():
    m.weight.data = w_init_t.clone().unsqueeze(0)
    m.bias.data = b_init_t.clone()
loss_fn = tr.nn.MSELoss(reduction='sum')
model.train()

optimizer = tr.optim.SGD(model.parameters(), lr = learning_rate)


for epoch in range(70):
    y_pred=model(x_t)
#     model.zero_grad()
    loss = loss_fn(y_pred , y_t)
    
    print("Progress: ", "epoch: ", epoch, "loss : ", loss.item())
    
    optimizer.zero_grad()
    
    loss.backward()
    
    
    optimizer.step()


print("Estimation of the parameters :  ")
for param in model.parameters():
    print(param)
    

Progress:  epoch:  0 loss :  55.44930648803711
Progress:  epoch:  1 loss :  41.74773025512695
Progress:  epoch:  2 loss :  36.386287689208984
Progress:  epoch:  3 loss :  31.89943504333496
Progress:  epoch:  4 loss :  27.991777420043945
Progress:  epoch:  5 loss :  24.583118438720703
Progress:  epoch:  6 loss :  21.60870933532715
Progress:  epoch:  7 loss :  19.012372970581055
Progress:  epoch:  8 loss :  16.7452392578125
Progress:  epoch:  9 loss :  14.764793395996094
Progress:  epoch:  10 loss :  13.034037590026855
Progress:  epoch:  11 loss :  11.520784378051758
Progress:  epoch:  12 loss :  10.197025299072266
Progress:  epoch:  13 loss :  9.038389205932617
Progress:  epoch:  14 loss :  8.023661613464355
Progress:  epoch:  15 loss :  7.134387493133545
Progress:  epoch:  16 loss :  6.354499816894531
Progress:  epoch:  17 loss :  5.670013904571533
Progress:  epoch:  18 loss :  5.068758964538574
Progress:  epoch:  19 loss :  4.540134906768799
Progress:  epoch:  20 loss :  4.07491540908

**Now its time to use the inbuilt pytorch function**


In [16]:
xb_t = tr.cat((x_t, tr.ones(30).unsqueeze(1)),1)
sol = tr.linalg.lstsq(xb_t, y_t)
sol.solution

tensor([[ 2.0000],
        [-3.0000],
        [ 1.0000]])

**One more Exercise**

In [17]:
x = random((300,2))
y = np.dot(x, [2.,-3.,]) + 1
x_t = tr.from_numpy(x).type(dtype)
y_t = tr.from_numpy(y).type(dtype).unsqueeze(1)



In [18]:
model = tr.nn.Sequential(
tr.nn.Linear(2,1))

for m in model.children():
    m.weight.data = w_init_t.clone().unsqueeze(0)
    m.bias.data = b_init_t.clone()
loss_fn = tr.nn.MSELoss(reduction='sum')
model.train()
optimizer = tr.optim.SGD(model.parameters(), lr = learning_rate)

for epoch in range(70):
    y_pred = model(x_t)
    loss = loss_fn(y_pred , y_t)
    
    print("Progress: ", "Epoch: ", epoch, "loss", loss.item())
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

print("Estimation of the parameter: ")
for param in model.parameters():
    print(param)

Progress:  Epoch:  0 loss 518.9248657226562
Progress:  Epoch:  1 loss 10265.5107421875
Progress:  Epoch:  2 loss 662972.5625
Progress:  Epoch:  3 loss 43262568.0
Progress:  Epoch:  4 loss 2823255296.0
Progress:  Epoch:  5 loss 184241717248.0
Progress:  Epoch:  6 loss 12023360389120.0
Progress:  Epoch:  7 loss 784627912409088.0
Progress:  Epoch:  8 loss 5.12037368144855e+16
Progress:  Epoch:  9 loss 3.341484831165907e+18
Progress:  Epoch:  10 loss 2.1806070515132636e+20
Progress:  Epoch:  11 loss 1.423034012047638e+22
Progress:  Epoch:  12 loss 9.286524753421497e+23
Progress:  Epoch:  13 loss 6.0602590243268e+25
Progress:  Epoch:  14 loss 3.9548411438525573e+27
Progress:  Epoch:  15 loss 2.5808750971096318e+29
Progress:  Epoch:  16 loss 1.6842432944602996e+31
Progress:  Epoch:  17 loss 1.0991140389448097e+33
Progress:  Epoch:  18 loss 7.172666182404813e+34
Progress:  Epoch:  19 loss 4.680782728059634e+36
Progress:  Epoch:  20 loss 3.0546144498375086e+38
Progress:  Epoch:  21 loss inf
Pr