In [20]:
import torch 
import torch.nn as nn

In [21]:
m = nn.Sigmoid()
loss = nn.BCELoss()
target = torch.empty(3).random_(2)
print(m, loss,target)

Sigmoid() BCELoss() tensor([0., 0., 1.])


In [22]:
input = torch.randn(3, requires_grad = True)
optimizer = torch.optim.SGD([input], lr = 0.1)
print(optimizer)
print(input,m(input))

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.1
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)
tensor([-2.2437,  0.0559, -2.6988], requires_grad=True) tensor([0.0959, 0.5140, 0.0630], grad_fn=<SigmoidBackward0>)


In [23]:
for _ in range(10000):
    output = loss(m(input), target)
    optimizer.zero_grad()
    output.backward()
    optimizer.step()

# print(m(target))

In [24]:
print(input, m(input), target,output, output.item())

tensor([-5.8267, -5.7946,  5.7839], requires_grad=True) tensor([0.0029, 0.0030, 0.9969], grad_fn=<SigmoidBackward0>) tensor([0., 0., 1.]) tensor(0.0030, grad_fn=<BinaryCrossEntropyBackward0>) 0.003018588526174426


In [30]:
target = torch.empty(1,2,3).random_(2)
print(target, target.ndim)


input = torch.randn((1,2,3), requires_grad = True)
optimizer = torch.optim.SGD([input], lr =0.1)
print(input, m(input).size(), input.ndim)

tensor([[[0., 0., 1.],
         [0., 1., 1.]]]) 3
tensor([[[-1.2865,  0.6694, -1.0972],
         [-0.3349, -1.5290,  3.2842]]], requires_grad=True) torch.Size([1, 2, 3]) 3


In [31]:
for _ in range(int(1e+4)):
    output = loss(m(input), target)
    optimizer.zero_grad()
    output.backward()
    optimizer.step()

In [32]:
print(input.ndim, m(input), target.ndim, target.size())

3 tensor([[[0.0060, 0.0062, 0.9938],
         [0.0061, 0.9938, 0.9948]]], grad_fn=<SigmoidBackward0>) 3 torch.Size([1, 2, 3])


In [33]:
target = torch.randn(3)
print(target, target.ndim)
input = torch.randn(3, requires_grad = True)
optimizer = torch.optim.SGD([input], lr = 0.1)
print(input, m(input))

tensor([-1.0594,  0.9742,  0.7941]) 1
tensor([-1.8155, -1.2058, -0.6906], requires_grad=True) tensor([0.1400, 0.2304, 0.3339], grad_fn=<SigmoidBackward0>)


In [34]:
for _ in range(10000):
    output = loss(m(input), target)
    optimizer.zero_grad()
    output.backward()
    optimizer.step()
    

In [35]:
print(m(input))

tensor([3.0439e-15, 9.7416e-01, 7.9409e-01], grad_fn=<SigmoidBackward0>)


In [36]:
target = 10 * torch.randn(3)
print(target, target.ndim)
input = torch.randn(3, requires_grad = True)
optimizer = torch.optim.SGD([input], lr = 0.1)
print(m(input), m(input).ndim)


tensor([-7.4967,  9.3365, -5.4339]) 1
tensor([0.8776, 0.1048, 0.4586], grad_fn=<SigmoidBackward0>) 1


In [37]:
for _ in range(10000):
    output = loss(m(input), target)
    optimizer.zero_grad()
    output.backward()
    optimizer.step()
    

In [38]:
print(m(input), input)

tensor([4.0457e-16, 1.0000e+00, 5.6001e-16], grad_fn=<SigmoidBackward0>) tensor([-35.4437,  16.7397, -35.1186], requires_grad=True)


In [40]:
loss2 = nn.BCEWithLogitsLoss()
target = torch.empty(3).random_(2)
print(target)

input = torch.randn(3, requires_grad=True)
optimizer = torch.optim.SGD([input], lr = 0.1)
for _ in range(500):
    output = loss2(m(input), target)
    optimizer.zero_grad()
    output.backward()
    optimizer.step()
print(m(input))


tensor([1., 0., 0.])
tensor([0.6392, 0.1411, 0.1559], grad_fn=<SigmoidBackward0>)


In [41]:
input = torch.randn(3, requires_grad=True)
optimizer = torch.optim.SGD([input], lr = 0.1)
for _ in range(500):
    output = loss2(input, target)
    optimizer.zero_grad()
    output.backward()
    optimizer.step()
print(m(input))


tensor([0.9283, 0.0598, 0.0577], grad_fn=<SigmoidBackward0>)


In [50]:
loss3 = nn.NLLLoss()
m3 = nn.LogSoftmax(dim=1)
target = torch.empty(4).random_(6)
print(target, target.size())

print(loss3, m3)

tensor([4., 2., 4., 0.]) torch.Size([4])
NLLLoss() LogSoftmax(dim=1)


In [48]:
input = torch.randn(4, requires_grad=True)
print(input.size())
optimizer = torch.optim.SGD([input], lr = 0.1)
for _ in range(1000):
    output = loss3(m3(input), target)
    optimizer.zero_grad()
    output.backward()
    optimizer.step()
print(torch.exp(m3(input)))


torch.Size([4])


IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [44]:
input = torch.randn((4,7), requires_grad=True)
optimizer = torch.optim.SGD([input], lr = 0.1)
for _ in range(1000):
    output = loss3(m3(input), target.long())
    optimizer.zero_grad()
    output.backward()
    optimizer.step()
print(torch.exp(m3(input)))


tensor([[3.9274e-03, 9.8357e-03, 9.6109e-01, 1.1168e-02, 3.7412e-03, 3.9155e-03,
         6.3175e-03],
        [1.0419e-02, 3.8518e-03, 8.3402e-03, 7.2220e-04, 8.8957e-03, 9.6109e-01,
         6.6850e-03],
        [6.8585e-03, 6.2846e-03, 6.3825e-03, 9.5937e-01, 5.9206e-03, 8.2393e-03,
         6.9468e-03],
        [9.6232e-01, 7.3816e-03, 2.6518e-03, 7.1855e-03, 4.5771e-03, 9.8900e-03,
         5.9923e-03]], grad_fn=<ExpBackward0>)


In [45]:
input = torch.randn((4,6), requires_grad=True)
optimizer = torch.optim.SGD([input], lr = 0.1)
for _ in range(1000):
    output = loss3(m3(input), target)
    optimizer.zero_grad()
    output.backward()
    optimizer.step()
print(torch.exp(m3(input)))


RuntimeError: expected scalar type Long but found Float

In [51]:
target = torch.empty(4,2,3).random_(6)
print(target)


tensor([[[5., 2., 0.],
         [5., 0., 5.]],

        [[3., 3., 2.],
         [1., 1., 5.]],

        [[2., 4., 2.],
         [0., 2., 0.]],

        [[5., 5., 3.],
         [4., 2., 5.]]])


In [52]:
loss4 = nn.CrossEntropyLoss()
m4 = nn.Softmax(dim=1)
target = torch.empty(4).random_(6)
input = torch.randn((4,6), requires_grad=True)
optimizer = torch.optim.SGD([input], lr = 0.1)


In [53]:
for _ in range(500):
    output = loss4(input, target.long())
    optimizer.zero_grad()
    output.backward()
    optimizer.step()
print(m4(input))


tensor([[0.9319, 0.0147, 0.0085, 0.0077, 0.0094, 0.0278],
        [0.9234, 0.0127, 0.0232, 0.0108, 0.0118, 0.0181],
        [0.0162, 0.0110, 0.0111, 0.9324, 0.0171, 0.0122],
        [0.0208, 0.0202, 0.0190, 0.9069, 0.0167, 0.0165]],
       grad_fn=<SoftmaxBackward0>)


In [54]:
for _ in range(500):
    output = loss3(input, target.long())
    optimizer.zero_grad()
    output.backward()
    optimizer.step()
print(m4(input))


tensor([[1.0000e+00, 5.8774e-08, 3.3940e-08, 3.0743e-08, 3.7584e-08, 1.1120e-07],
        [1.0000e+00, 5.1413e-08, 9.3521e-08, 4.3675e-08, 4.7461e-08, 7.3216e-08],
        [6.4918e-08, 4.3796e-08, 4.4362e-08, 1.0000e+00, 6.8545e-08, 4.8785e-08],
        [8.5539e-08, 8.2937e-08, 7.7973e-08, 1.0000e+00, 6.8545e-08, 6.7806e-08]],
       grad_fn=<SoftmaxBackward0>)


In [55]:
for _ in range(500):
    output = loss3(m3(input), target.long())
    optimizer.zero_grad()
    output.backward()
    optimizer.step()
print(torch.exp(m3(input)))


tensor([[1.0000e+00, 5.8774e-08, 3.3940e-08, 3.0743e-08, 3.7584e-08, 1.1120e-07],
        [1.0000e+00, 5.1413e-08, 9.3521e-08, 4.3675e-08, 4.7461e-08, 7.3215e-08],
        [6.4918e-08, 4.3796e-08, 4.4362e-08, 1.0000e+00, 6.8545e-08, 4.8785e-08],
        [8.5539e-08, 8.2937e-08, 7.7973e-08, 1.0000e+00, 6.8545e-08, 6.7806e-08]],
       grad_fn=<ExpBackward0>)
